FROM node:14-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN npm install -g nodemon && npm install -g typescript 



# Exports
EXPOSE 3000
CMD [ "npm", "run", "start.dev" ]